### ISSUE TITLE
Supprimez vos branches après qu'elles aient été "merged" suite à un "pull request"

### ISSUE THREAD

**Issue by PHingamp** [PHingamp/L3PGF-visuOmics#7]
Je vous conseille de supprimer les branches après que les modifs que vous aez faites ont été intégrée dans la branche Master suite à un Pull Request validé. Sinon votre branche indépendante va peu à peu risquer de se désynchroniser de la branche "Master" (car un Pull Request intègre les changements de votre branche privée vers la branche Master, mais pas l'inverse...).
Le cycle ressemble donc à : 
* Créer une branche privée à partir du Master (la nommer avec l'objet des modifs projetées)
* modifier les fichiers dans sa branche privée
* faire un pull request quand vous voulez intégrer vos modifs dans la branche Master
* attendre que je valide le Pull Request afin de "merger" vos modifs dans le Master
* supprimer votre branche privée
* repartir au premier point de cette liste...

**Comment by Elise-11** [comment]
Ok

**Comment by PHingamp** [comment]
Du coup j'ai supprimé la branche "Heatmap" qui a déjà été fusionnée.
